chore(ci): CI with GitHub Actions
dashevo/js-dpns-client pull request #12
Opened 2021-04-26 11:14 UTC by strophy

## Issue being fixed or feature implemented

We experiencing several problems with Travis CI. It is slow and does not allow to restart builds.

## What was done?

- Introduce Github Action workflows for running tests and releasing.
- Delete Travis scripts
- Update badges
- Fix invalid readme syntax

## How Has This Been Tested?

With Github Actions

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-04-26 12:23 UTC, shumkov approved these changes
👍

2021-04-26 12:24 UTC, shumkov requested changes
It seems functional tests require local network.

2021-04-26 17:21 UTC, strophy commented
I tried starting a local network both on my local machine and in CI, but always get this error:
```
  0 passing (27s)
  2 failing

  1) DPNS client
       "before each" hook for "should be able to register and resolve a domain":
     Error: connect ECONNREFUSED 127.0.0.1:55582
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)

  2) DPNS client
       "after each" hook for "should be able to register and resolve a domain":
     TypeError: Cannot read property 'remove' of undefined
      at Context.<anonymous> (test/functional/dpnsClient.spec.js:275:24)
      at processImmediate (internal/timers.js:461:21)
```

What does it expect to find on this port, and where is the port defined?

2021-04-27 08:19 UTC, shumkov commented
@strophy My bad. We don't need the local network here. The functional tests in this repo using obsolete https://github.com/dashevo/js-dp-services-ctl to start DAPI instances.

I would just skip functional tests for now. To do that, you need to replace `describe` to `describe.skip` in this line https://github.com/dashevo/js-dpns-client/blob/v0.2-dev/test/functional/dpnsClient.spec.js#L108

2021-04-27 11:17 UTC, shumkov requested changes

2021-04-27 11:17 UTC, shumkov commented on .github/workflows/.env
> +#DRIVE_BRANCH=
We don’t need it since we are not using mn bootsteap

2021-04-27 11:17 UTC, shumkov commented on .github/workflows/test_and_release.yml
> +    timeout-minutes: 60
10?

2021-04-27 11:21 UTC, strophy commented
OK, I made the changes. I wonder if it is possible to include the grpc build in the cache? Currently it says this:
```
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.2 and node@12.22.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
```

Also I just added [new CI](https://github.com/dashevo/js-dp-services-ctl/pull/132) to that obsolete `js-dp-services-ctl` repo, should we archive it instead?

2021-04-27 11:26 UTC, shumkov commented
Yeah, you can use the node-gyp-cache npm package as we are doing in Drive and DAPI.

We will archive dp-services-crl when we remove it from everywhere.

2021-04-27 11:27 UTC, shumkov approved these changes
👍

2021-04-27 11:27 UTC, merged